/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Mago(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("../models/mago.gltf");
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null} position={[0,0.15,0]}>
      <group name="Scene">
        <group name="Armature_druide" scale={1}>
          <primitive object={nodes.root} />
          <skinnedMesh
            name="druid"
            geometry={nodes.druid.geometry}
            material={materials.color_main}
            skeleton={nodes.druid.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../models/mago.gltf");